os: linux
language: python
python:
  - "3.4"
before_install:
- export PATH="$HOME/pandoc:$PATH"
- mkdir $HOME/pandoc
- curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
- unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc -d $HOME/pandoc
- chmod +x $HOME/pandoc/pandoc
- pandoc --version
- rm pandoc-1.12.3.zip
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml
  - source activate PGE310
compiler:
  - gcc
script: 
  - nikola build
after_success: 
    # Get to the Travis build directory, configure git and clone the repo
    - cd $HOME
    - git config --global user.email ${GH_EMAIL}
    - git config --global user.name ${GH_NAME}
    # Commit and Push the Changes
    - git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/johnfoster-pge-utexas/PGE310-IntroProgramming gh-pages > /dev/null
    - cd gh-pages
    - cp -Rf $HOME/build/johnfoster-pge-utexas/PGE310-IntroProgramming/output/* .
    - git add -A
    - git commit -m "Travis CI autocommit from travis build $TRAVIS_BUILD_NUMBER"
    - git push -fq origin gh-pages > /dev/null
    - git push -fq https://${GH_TOKEN}@github.com/johntfoster/PGE310-IntroProgramming gh-pages
